/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-11 14:51:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profile_005fmy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1651196450364L));
    _jspx_dependants.put("jar:file:/C:/workspace/5_Server/moochelinGuide/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>내 프로필</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- 그래프css  -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/analysis.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 헤더푸터 CSS 연결-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main-style-white.css\">\r\n");
      out.write("    <!-- 마이페이지 CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/myPage-style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 기본헤더 투명헤더에 기본헤더의 값이 있기때문에 활성화X-->\r\n");
      out.write("    <!-- <link  id=\"cssTest1\" rel=\"stylesheet\" href=\"../ksj/css/main-style.css\"> -->\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/profile_my.css\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/e4f51ae88c.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Black+Han+Sans&family=Dongle&family=Gowun+Batang&family=Noto+Sans+KR:wght@100;300;400;500;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header_white.jsp", out, false);
      out.write(" \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <main> \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <section class=\"page-start\">\r\n");
      out.write("                <div class=\"my-background\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"info-1200px\">\r\n");
      out.write("                    <div class=\"info-center-flex\">\r\n");
      out.write("                        <!-- 배경이미지 / 내프로필 / 팔로워/팔로잉 .... 평가한 영화 -->\r\n");
      out.write("                        <div class=\"profile-position profile-img-area\">\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						\r\n");
      out.write("						");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				\r\n");
      out.write("                            <!-- <div class=\"fa-solid fa-user\"></div> -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"profile-name\">김유저</div>\r\n");
      out.write("                            <div class=\"follow\"><span><a href=\"#\">팔로워</a> : 3</span><span>   |   </span><span><a href=\"#\">팔로잉</a>  : 3</span></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 제가 마이페이지에 a태그 넣어서 깨져버렸어용-->\r\n");
      out.write("                        <div class=\"mypage-button\"> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/myPage/mod\">마이페이지</a> </div>\r\n");
      out.write("                        <div class=\"pick-heart\">❤</div>\r\n");
      out.write("                        <div class=\"bucket-list\">찜한 영화 30</div>\r\n");
      out.write("                        <div class=\"count-star\">⭐</div>\r\n");
      out.write("                        <div class=\"moovie-analysis\">평가한 영화 533</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            \r\n");
      out.write("            <!-- 내가 평가한 영화 / 내가 찜한 영화 / 취향분석 -->\r\n");
      out.write("            <section class=\"sec-content\">\r\n");
      out.write("                <div class=\"info-1200px\">    \r\n");
      out.write("                        <div class=\"title-area\">\r\n");
      out.write("                            <div class=\"title content-analysis\"> 내가 평가한 영화 </div>\r\n");
      out.write("                            <div class=\"more-view\"><a href=\"#\"> +더보기 </a></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-list-all\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"movie\">\r\n");
      out.write("                                            <div class=\"movie-top\">\r\n");
      out.write("                                                <div class=\"movie-poster\">\r\n");
      out.write("                                                    <img src=\"resources/images/VFz7DVf6CB4HlTlfxNx3vw.jpg\" alt=\"\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"movie-bottom\">\r\n");
      out.write("                                                <div class=\"movie-title\">브로커</div>\r\n");
      out.write("                                                <div class=\"movie-year-contry\">2022 ・ 한국</div>\r\n");
      out.write("                                                <div class=\"average\">\r\n");
      out.write("                                                    <span>평균</span>\r\n");
      out.write("                                                    <svg width=\"12\" height=\"10\" viewBox=\"0 0 12 10\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"#555765\" class=\"css-1g90l0x\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M6 8.02L3.14233 9.91131C2.91094 10.0644 2.61352 9.84836 2.68767 9.58097L3.60334 6.27872L0.921531 4.14536C0.704379 3.97262 0.817982 3.62299 1.0952 3.61087L4.51878 3.46128L5.719 0.251483C5.81619 -0.00842059 6.18381 -0.00842094 6.281 0.251483L7.48122 3.46128L10.9048 3.61087C11.182 3.62299 11.2956 3.97262 11.0785 4.14536L8.39666 6.27872L9.31233 9.58097C9.38648 9.84836 9.08906 10.0644 8.85767 9.91131L6 8.02Z\"></path></svg>\r\n");
      out.write("                                                    <span>3.8</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("            \r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"movie\">\r\n");
      out.write("                                            <div class=\"movie-top\">\r\n");
      out.write("                                                <div class=\"movie-poster\">\r\n");
      out.write("                                                    <img src=\"../images/broker.jpeg\" alt=\"\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"movie-bottom\">\r\n");
      out.write("                                                <div class=\"movie-title\">닥터 스트레인지: 대혼돈의 멀티버스</div>\r\n");
      out.write("                                                <div class=\"movie-year-contry\">2022 ・ 미국</div>\r\n");
      out.write("                                                <div class=\"average\">\r\n");
      out.write("                                                    <span>평균</span>\r\n");
      out.write("                                                    <svg width=\"12\" height=\"10\" viewBox=\"0 0 12 10\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"#555765\" class=\"css-1g90l0x\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M6 8.02L3.14233 9.91131C2.91094 10.0644 2.61352 9.84836 2.68767 9.58097L3.60334 6.27872L0.921531 4.14536C0.704379 3.97262 0.817982 3.62299 1.0952 3.61087L4.51878 3.46128L5.719 0.251483C5.81619 -0.00842059 6.18381 -0.00842094 6.281 0.251483L7.48122 3.46128L10.9048 3.61087C11.182 3.62299 11.2956 3.97262 11.0785 4.14536L8.39666 6.27872L9.31233 9.58097C9.38648 9.84836 9.08906 10.0644 8.85767 9.91131L6 8.02Z\"></path></svg>\r\n");
      out.write("                                                    <span>3.3</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("            \r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"movie\">\r\n");
      out.write("                                            <div class=\"movie-top\">\r\n");
      out.write("                                                <div class=\"movie-poster\">\r\n");
      out.write("                                                    <img src=\"../images/broker.jpeg\" alt=\"\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"movie-bottom\">\r\n");
      out.write("                                                <div class=\"movie-title\">닥터 스트레인지: 대혼돈의 멀티버스</div>\r\n");
      out.write("                                                <div class=\"movie-year-contry\">2022 ・ 미국</div>\r\n");
      out.write("                                                <div class=\"average\">\r\n");
      out.write("                                                    <span>평균</span>\r\n");
      out.write("                                                    <svg width=\"12\" height=\"10\" viewBox=\"0 0 12 10\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"#555765\" class=\"css-1g90l0x\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M6 8.02L3.14233 9.91131C2.91094 10.0644 2.61352 9.84836 2.68767 9.58097L3.60334 6.27872L0.921531 4.14536C0.704379 3.97262 0.817982 3.62299 1.0952 3.61087L4.51878 3.46128L5.719 0.251483C5.81619 -0.00842059 6.18381 -0.00842094 6.281 0.251483L7.48122 3.46128L10.9048 3.61087C11.182 3.62299 11.2956 3.97262 11.0785 4.14536L8.39666 6.27872L9.31233 9.58097C9.38648 9.84836 9.08906 10.0644 8.85767 9.91131L6 8.02Z\"></path></svg>\r\n");
      out.write("                                                    <span>3.3</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("            \r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"movie\">\r\n");
      out.write("                                            <div class=\"movie-top\">\r\n");
      out.write("                                                <div class=\"movie-poster\">\r\n");
      out.write("                                                    <img src=\"../images/VFz7DVf6CB4HlTlfxNx3vw.jpg\" alt=\"\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"movie-bottom\">\r\n");
      out.write("                                                <div class=\"movie-title\">닥터 스트레인지: 대혼돈의 멀티버스</div>\r\n");
      out.write("                                                <div class=\"movie-year-contry\">2022 ・ 미국</div>\r\n");
      out.write("                                                <div class=\"average\">\r\n");
      out.write("                                                    <span>평균</span>\r\n");
      out.write("                                                    <svg width=\"12\" height=\"10\" viewBox=\"0 0 12 10\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"#555765\" class=\"css-1g90l0x\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M6 8.02L3.14233 9.91131C2.91094 10.0644 2.61352 9.84836 2.68767 9.58097L3.60334 6.27872L0.921531 4.14536C0.704379 3.97262 0.817982 3.62299 1.0952 3.61087L4.51878 3.46128L5.719 0.251483C5.81619 -0.00842059 6.18381 -0.00842094 6.281 0.251483L7.48122 3.46128L10.9048 3.61087C11.182 3.62299 11.2956 3.97262 11.0785 4.14536L8.39666 6.27872L9.31233 9.58097C9.38648 9.84836 9.08906 10.0644 8.85767 9.91131L6 8.02Z\"></path></svg>\r\n");
      out.write("                                                    <span>3.3</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("            \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("            \r\n");
      out.write("                        <div class=\"title-area\">\r\n");
      out.write("                            <div class=\"title content-analysis\"> 내가 찜한 영화 </div>\r\n");
      out.write("                            <div class=\"more-view\"><a href=\"#\"> +더보기 </a></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"movie-list-all\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"movie\">\r\n");
      out.write("                                            <div class=\"movie-top\">\r\n");
      out.write("                                                <div class=\"movie-poster\">\r\n");
      out.write("                                                    <img src=\"../images/broker.jpeg\" alt=\"\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"movie-bottom\">\r\n");
      out.write("                                                <div class=\"movie-title\">브로커</div>\r\n");
      out.write("                                                <div class=\"movie-year-contry\">2022 ・ 한국</div>\r\n");
      out.write("                                                <div class=\"average\">\r\n");
      out.write("                                                    <span>평균</span>\r\n");
      out.write("                                                    <svg width=\"12\" height=\"10\" viewBox=\"0 0 12 10\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"#555765\" class=\"css-1g90l0x\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M6 8.02L3.14233 9.91131C2.91094 10.0644 2.61352 9.84836 2.68767 9.58097L3.60334 6.27872L0.921531 4.14536C0.704379 3.97262 0.817982 3.62299 1.0952 3.61087L4.51878 3.46128L5.719 0.251483C5.81619 -0.00842059 6.18381 -0.00842094 6.281 0.251483L7.48122 3.46128L10.9048 3.61087C11.182 3.62299 11.2956 3.97262 11.0785 4.14536L8.39666 6.27872L9.31233 9.58097C9.38648 9.84836 9.08906 10.0644 8.85767 9.91131L6 8.02Z\"></path></svg>\r\n");
      out.write("                                                    <span>3.8</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("            \r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"movie\">\r\n");
      out.write("                                            <div class=\"movie-top\">\r\n");
      out.write("                                                <div class=\"movie-poster\">\r\n");
      out.write("                                                    <img src=\"../images/VFz7DVf6CB4HlTlfxNx3vw.jpg\" alt=\"\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"movie-bottom\">\r\n");
      out.write("                                                <div class=\"movie-title\">닥터 스트레인지: 대혼돈의 멀티버스</div>\r\n");
      out.write("                                                <div class=\"movie-year-contry\">2022 ・ 미국</div>\r\n");
      out.write("                                                <div class=\"average\">\r\n");
      out.write("                                                    <span>평균</span>\r\n");
      out.write("                                                    <svg width=\"12\" height=\"10\" viewBox=\"0 0 12 10\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"#555765\" class=\"css-1g90l0x\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M6 8.02L3.14233 9.91131C2.91094 10.0644 2.61352 9.84836 2.68767 9.58097L3.60334 6.27872L0.921531 4.14536C0.704379 3.97262 0.817982 3.62299 1.0952 3.61087L4.51878 3.46128L5.719 0.251483C5.81619 -0.00842059 6.18381 -0.00842094 6.281 0.251483L7.48122 3.46128L10.9048 3.61087C11.182 3.62299 11.2956 3.97262 11.0785 4.14536L8.39666 6.27872L9.31233 9.58097C9.38648 9.84836 9.08906 10.0644 8.85767 9.91131L6 8.02Z\"></path></svg>\r\n");
      out.write("                                                    <span>3.3</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("            \r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"movie\">\r\n");
      out.write("                                            <div class=\"movie-top\">\r\n");
      out.write("                                                <div class=\"movie-poster\">\r\n");
      out.write("                                                    <img src=\"../images/broker.jpeg\" alt=\"\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"movie-bottom\">\r\n");
      out.write("                                                <div class=\"movie-title\">닥터 스트레인지: 대혼돈의 멀티버스</div>\r\n");
      out.write("                                                <div class=\"movie-year-contry\">2022 ・ 미국</div>\r\n");
      out.write("                                                <div class=\"average\">\r\n");
      out.write("                                                    <span>평균</span>\r\n");
      out.write("                                                    <svg width=\"12\" height=\"10\" viewBox=\"0 0 12 10\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"#555765\" class=\"css-1g90l0x\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M6 8.02L3.14233 9.91131C2.91094 10.0644 2.61352 9.84836 2.68767 9.58097L3.60334 6.27872L0.921531 4.14536C0.704379 3.97262 0.817982 3.62299 1.0952 3.61087L4.51878 3.46128L5.719 0.251483C5.81619 -0.00842059 6.18381 -0.00842094 6.281 0.251483L7.48122 3.46128L10.9048 3.61087C11.182 3.62299 11.2956 3.97262 11.0785 4.14536L8.39666 6.27872L9.31233 9.58097C9.38648 9.84836 9.08906 10.0644 8.85767 9.91131L6 8.02Z\"></path></svg>\r\n");
      out.write("                                                    <span>3.3</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("            \r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <div class=\"movie\">\r\n");
      out.write("                                            <div class=\"movie-top\">\r\n");
      out.write("                                                <div class=\"movie-poster\">\r\n");
      out.write("                                                    <img src=\"../images/VFz7DVf6CB4HlTlfxNx3vw.jpg\" alt=\"\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"movie-bottom\">\r\n");
      out.write("                                                <div class=\"movie-title\">닥터 스트레인지: 대혼돈의 멀티버스</div>\r\n");
      out.write("                                                <div class=\"movie-year-contry\">2022 ・ 미국</div>\r\n");
      out.write("                                                <div class=\"average\">\r\n");
      out.write("                                                    <span>평균</span>\r\n");
      out.write("                                                    <svg width=\"12\" height=\"10\" viewBox=\"0 0 12 10\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"#555765\" class=\"css-1g90l0x\"><path fill-rule=\"evenodd\" clip-rule=\"evenodd\" d=\"M6 8.02L3.14233 9.91131C2.91094 10.0644 2.61352 9.84836 2.68767 9.58097L3.60334 6.27872L0.921531 4.14536C0.704379 3.97262 0.817982 3.62299 1.0952 3.61087L4.51878 3.46128L5.719 0.251483C5.81619 -0.00842059 6.18381 -0.00842094 6.281 0.251483L7.48122 3.46128L10.9048 3.61087C11.182 3.62299 11.2956 3.97262 11.0785 4.14536L8.39666 6.27872L9.31233 9.58097C9.38648 9.84836 9.08906 10.0644 8.85767 9.91131L6 8.02Z\"></path></svg>\r\n");
      out.write("                                                    <span>3.3</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("            \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("            \r\n");
      out.write("                        <div>\r\n");
      out.write("                                <div class=\"title content-analysisn\"> 취향분석 </div>\r\n");
      out.write("                                <div class=\"more-view anal\"> \"평점 3.79점의 까탈 영화 사랑꾼\" </div>\r\n");
      out.write("\r\n");
      out.write("                                 <!-- 평점 그래프 -->\r\n");
      out.write("                                <div class=\"sec-in-block\">\r\n");
      out.write("                                    <div class=\"set-area\">\r\n");
      out.write("                                        <ul class=\"graph-around\">\r\n");
      out.write("                                            <li><div></div></li>\r\n");
      out.write("                                            <li><div></div></li>\r\n");
      out.write("                                            <li><div></div></li>\r\n");
      out.write("                                            <li><div></div></li>\r\n");
      out.write("                                            <li><div></div></li>\r\n");
      out.write("                                            <li><div></div></li>\r\n");
      out.write("                                            <li><div></div></li>\r\n");
      out.write("                                            <li><div></div></li>\r\n");
      out.write("                                            <li><div></div></li>\r\n");
      out.write("                                            <li><div></div></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"set-area-1\">\r\n");
      out.write("                                        <ul class=\"around\">\r\n");
      out.write("                                            <li></li>\r\n");
      out.write("                                            <li>1</li>\r\n");
      out.write("                                            <li></li>\r\n");
      out.write("                                            <li>2</li>\r\n");
      out.write("                                            <li></li>\r\n");
      out.write("                                            <li>3</li>\r\n");
      out.write("                                            <li></li>\r\n");
      out.write("                                            <li>4</li>\r\n");
      out.write("                                            <li></li>\r\n");
      out.write("                                            <li>5</li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"button\" onclick=\"location.href='analysis.jsp'\" class=\"anal-button\" >취향분석 보기</button>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/header_white.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/member/profile_my.jsp(50,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginMember.profileImage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<li class=\"profile\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/myPage/mod\"><div id=\"profileImage\"></div></a></li>						\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/member/profile_my.jsp(54,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginMember.profileImage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<li class=\"profile\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/myPage/mod\"><div id=\"profileImage\" style=\" background-size: 40px; background-image : url(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.profileImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\"></div></a></li>						\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
